### ISSUE TITLE
Why Internet Explorer takes more time to render templates?

### ISSUE THREAD

**Issue by KarthikaDevi** [wycats/handlebars-site#132]
Hi,
  I am using handlebar templates(precompiled) to render content inside list item (&lt;li&gt;) present in an unordered list.
   For eg.   
     &lt; li &gt; 
       &lt; span class="someName" &gt; Bold Icon  &lt; /span &gt;
      &lt; span class="someName" &gt; Bold  &lt; /span &gt;
     &lt; /li &gt;
In Firefox and Chrome, for a unordered list of nearly 24 items, only the first item rendering took about 4 milliseconds and remaining items took approximately 0.2 milliseconds. But in IE, each list item rendering takes the same amount of time(5 milliseconds each) which increases the overall rendering time. Is this an issue? Whether Internet Explorer cache the templates or not?

**Comment by kpdecker** [comment]
IE, particularly older version, has a slower javascript engine. There isn't much that we can do to work around that. WRT caching of templates, all browsers should have the same behavior. If you are seeing otherwise then we're glad to take a look if you can show us logs or profiling data.

Closing this as we can't fix IE's issues directly here.
