### ISSUE TITLE
handlebars.js is dropping divs from a template

### ISSUE THREAD

**Issue by bradlymathews** [wycats/handlebars-site#173]
handlebars is not outputting all of the end div tags in my template.

Here is a template snippet:

    <div class="leftLineBottom"></div>
      </div>   
        </div>      
          
Most of the time it works, but other times it will output:

    <div class="leftLineBottom"></div>
      </div>   
        

The last closing div tag is missing.

Another snippet from the same template:

          </div>      
        {{/each}}
      {{/each}}   
    {{/if}}  
      </div> 
      </div>

 But both end div tags are missing from the final html:

    </div>
    
    

This is obviously causing some render issues.

Any clues or ideas for further debugging?

Thanks

**Comment by nknapp** [comment]
Such problems are usually cause by the browser DOM. Handlebars does not have anything to do with it, because it only works with strings, not elements.

Make sure you have your template inside a `<script>`-tag, like shown on http://handlebarsjs.com/. 
I would look at it if you set up a jsfiddle https://jsfiddle.net/9D88g/113/ to reproduce the issue.
