### ISSUE TITLE
No table of contents -- hard to navigate

### ISSUE THREAD

**Issue by purplejacket** [wycats/handlebars-site#180]
It's hard to navigate the documentation pages.  There's no obvious table of contents pane or such.  If I do a google search and get deep linked into some doc page, there's no natural way to reach the rest of the doc.

**Comment by nknapp** [comment]
Yes, we are about to start with creating a new site, I hope. https://github.com/wycats/handlebars.js/issues/1345

**Comment by ffxsam** [comment]
How's progress on this?

**Comment by nknapp** [comment]
Stalling... To me, it's a problem of too many different things to do. Anyone who want's to give it a start, is welcome to come aboard.

**Comment by LarryAzevedo** [comment]
I could do a wireframe if you think that would be helpful (baby-steps).

**Comment by jpveilleux** [comment]
> Command+F

What a dumb thing to say... you must be the same guy who answers "Use Firefox/Chrome" when someone has an issue in IE for his site/app development...

**Comment by nknapp** [comment]
new site is up. It has a search box and a navigation

**Comment by nknapp** [comment]
I find the request for very comprehensible. We didn't have an official "code of conduct" at that time, which is why I am not removing the comment (at least not now). But "Command + F" is indeed not helpful (and it really did not help much on the old site, because there were multiple pages and no global search) and "you must be the same guy who answers..." is a personal attack. We don't need either here.
