### ISSUE TITLE
Use handlebars with ES6 modules import statement

### ISSUE THREAD

**Issue by Nock-zz** [wycats/handlebars-site#213]
I am trying to use handlebars with an ES6 modules import statement.
I cannot get it to work and confess I do not understand root.Handlebars etc..
I am getting: Uncaught TypeError: Cannot read property 'Handlebars' of undefined
handlebars.js:34 
root.Handlebars = root.Handlebars || factory();
and handlebars.js:36.
}(this, function () { 

Do you have any suggestions on how this could be done?

**Comment by nknapp** [comment]
Are you using webpack? Have a look at this integration test then https://github.com/wycats/handlebars.js/tree/master/integration-testing/webpack-test

Otherwise, please prepare a minimal example of what you are doing and explain 

* your environment (browser, node)
* your tools
* and show how your code looks like.
