### ISSUE TITLE
zero width space

### ISSUE THREAD

**Issue by stiengenterprises** [wycats/handlebars-site#95]
See my issue over at Stackoverflow:
http://stackoverflow.com/questions/28738650/why-am-i-getting-this-weird-8203-line-break/28741288#28741288

In short: When  I get the content of the javascript string, I get *zero width space* values. This is not filtered by Handlebars. So when I append the result to the DOM, I get unwanted space.

My solution was to use regex to remove *zero width space*:

`var source = $("#guideListTemplate").html().replace(/[\u200B]/g, '');`

I think this is a bug as Handlebars should remove *zero width space*.

**Comment by kpdecker** [comment]
Handlebars generally tries to be agnostic to the content that it is rendering so we aren't going to arbitrarily strip out content from the result as there are use cases where people will want this character. I would recommend doing what you are already doing now or remove the zero width space characters from the input template if you are having issues due to them.

**Comment by stiengenterprises** [comment]
I understand that. But you are wrapping templates inside script tags   
   `<script id="entry-template" type="text/x-handlebars-template">`
and for some reason, that adds *zero width space*. It's not space that the users want in their code. So Handlebars forces me to write code to remove unwanted characters that I'm not generating.

**Comment by kpdecker** [comment]
That is not a function of handlebars, but one of how you at loading. I'm
not sure why that may be occurring, but I would recommend using the
precompiler rather than embedding in a script tag.
